### PR TITLE
fish pepper the fixed JMX exporter quoted property values

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@alexkieling I just noticed that your #194 was incomplete (I should have noticed this during review, or we should automate it, see #120) ... you had fixed up `java/blocks/jmxexporter/fp-files/prometheus-config.yml` and `karaf/blocks/jmxexporter/fp-files/prometheus-config.yml` but did not re-run `fish-pepper`, in both `java/` and `karaf/` and check those generated files in... this PR remedies that. Hope this makes sense and OK for you if I merge this?

@rhuss FYI

**Comment by alexkieling** [comment]
@vorburger I was having issues running `fish-pepper` and @rhuss told me I could submit the changes to those files and he (or somebody else) would run `fish-pepper`. By the way, how did you run `fish-pepper` so I know what to do next time?

**Comment by vorburger** [comment]
> was having issues running fish-pepper 

That was #13 right? I "interpreted" that you were fine after that.

> By the way, how did you run fish-pepper so I know what to do next time?

like this:

    cd java/ ; fish-pepper; cd ../karaf; fish-pepper

that's all there is to it! :smile_cat:

**Comment by alexkieling** [comment]
@vorburger Would add those commands to a `build.sh` file make sense?

**Pull request merged**
