### PR TITLE
Another attempt at using the SCL version of mvn.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by rhuss** [comment]
Actually switching to SCL version of mvn brings in these extra packages:

<details><summary>Package List</summary>
```
GConf2                             x86_64 3.2.6-8.el7     base           1.0 M
 atk                                x86_64 2.14.0-1.el7    base           251 k
 avahi-libs                         x86_64 0.6.31-17.el7   base            61 k
 cairo                              x86_64 1.14.2-1.el7    base           711 k
 copy-jdk-configs                   noarch 1.2-1.el7       base            14 k
 cups-libs                          x86_64 1:1.6.3-26.el7  base           356 k
 flac-libs                          x86_64 1.3.0-5.el7_1   base           169 k
 gdk-pixbuf2                        x86_64 2.31.6-3.el7    base           559 k
 graphite2                          x86_64 1.3.6-1.el7_2   base           112 k
 gsm                                x86_64 1.0.13-11.el7   base            30 k
 gtk2                               x86_64 2.24.28-8.el7   base           3.4 M
 harfbuzz                           x86_64 0.9.36-1.el7    base           156 k
 hicolor-icon-theme                 noarch 0.12-7.el7      base            42 k
 hwdata                             x86_64 0.252-8.4.el7   base           2.1 M
 jasper-libs                        x86_64 1.900.1-29.el7  base           149 k
 java-1.7.0-openjdk                 x86_64 1:1.7.0.121-2.6.8.0.el7_3
                                                           updates        230 k
 java-1.7.0-openjdk-devel           x86_64 1:1.7.0.121-2.6.8.0.el7_3
                                                           updates        9.1 M
 java-1.7.0-openjdk-headless        x86_64 1:1.7.0.121-2.6.8.0.el7_3
                                                           updates         25 M
 jbigkit-libs                       x86_64 2.0-11.el7      base            46 k
 json-c                             x86_64 0.11-4.el7_0    base            31 k
 libXcomposite                      x86_64 0.4.4-4.1.el7   base            22 k
 libXcursor                         x86_64 1.1.14-2.1.el7  base            30 k
 libXdamage                         x86_64 1.1.4-4.1.el7   base            20 k
 libXfixes                          x86_64 5.0.1-2.1.el7   base            18 k
 libXft                             x86_64 2.3.2-2.el7     base            58 k
 libXinerama                        x86_64 1.1.3-2.1.el7   base            14 k
 libXrandr                          x86_64 1.4.2-2.el7     base            26 k
 libXxf86vm                         x86_64 1.1.3-2.1.el7   base            17 k
 libasyncns                         x86_64 0.8-7.el7       base            26 k
 libdrm                             x86_64 2.4.67-3.el7    base           141 k
 libogg                             x86_64 2:1.3.0-7.el7   base            24 k
 libpciaccess                       x86_64 0.13.4-2.el7    base            26 k
 libsndfile                         x86_64 1.0.25-10.el7   base           149 k
 libthai                            x86_64 0.1.14-9.el7    base           187 k
 libtiff                            x86_64 4.0.3-25.el7_2  base           169 k
 libvorbis                          x86_64 1:1.3.3-8.el7   base           204 k
 libxshmfence                       x86_64 1.2-1.el7       base           7.2 k
 mesa-libEGL                        x86_64 11.2.2-2.20160614.el7
                                                           base            85 k
 mesa-libGL                         x86_64 11.2.2-2.20160614.el7
                                                           base           162 k
 mesa-libgbm                        x86_64 11.2.2-2.20160614.el7
                                                           base            42 k
 mesa-libglapi                      x86_64 11.2.2-2.20160614.el7
                                                           base            40 k
 mozjs17                            x86_64 17.0.0-19.el7   base           1.4 M
 pango                              x86_64 1.36.8-2.el7    base           287 k
 pcsc-lite-libs                     x86_64 1.8.8-6.el7     base            34 k
 pixman                             x86_64 0.34.0-1.el7    base           248 k
 polkit                             x86_64 0.112-9.el7     base           166 k
 polkit-pkla-compat                 x86_64 0.1-4.el7       base            39 k
 psmisc                             x86_64 22.20-11.el7    base           141 k
 pulseaudio-libs                    x86_64 6.0-8.el7       base           581 k
 rh-java-common-PyXB                noarch 1.2.4-1.4.el7   centos-sclo-rh 505 k
 rh-java-common-aopalliance         noarch 1.0-8.10.el7    centos-sclo-rh  12 k
 rh-java-common-apache-commons-cli  noarch 1.2-13.12.el7   centos-sclo-rh  51 k
 rh-java-common-apache-commons-codec
                                    noarch 1.8-7.12.el7    centos-sclo-rh 223 k
 rh-java-common-apache-commons-io   noarch 1:2.4-12.11.el7 centos-sclo-rh 188 k
 rh-java-common-apache-commons-lang noarch 2.6-15.11.el7   centos-sclo-rh 276 k
 rh-java-common-apache-commons-logging
                                    noarch 1.1.2-7.15.el7  centos-sclo-rh  77 k
 rh-java-common-atinject            noarch 1-13.20100611svn86.10.el7
                                                           centos-sclo-rh  14 k
 rh-java-common-geronimo-annotation noarch 1.0-15.12.el7   centos-sclo-rh  23 k
 rh-java-common-guava               noarch 13.0-6.12.el7   centos-sclo-rh 1.6 M
 rh-java-common-httpcomponents-client
                                    noarch 4.3.6-1.2.el7   centos-sclo-rh 574 k
 rh-java-common-httpcomponents-core noarch 4.3.3-1.3.el7   centos-sclo-rh 540 k
 rh-java-common-javapackages-tools  noarch 4.3.2-1.11.el7  centos-sclo-rh  94 k
 rh-java-common-jsoup               noarch 1.6.1-10.10.el7 centos-sclo-rh 263 k
 rh-java-common-objectweb-asm5      noarch 5.0.3-1.4.el7   centos-sclo-rh 574 k
 rh-java-common-python-javapackages noarch 4.3.2-1.11.el7  centos-sclo-rh  86 k
 rh-java-common-runtime             x86_64 1.1-46.el7      centos-sclo-rh  30 k
 rh-java-common-slf4j               noarch 1.7.4-3.22.el7  centos-sclo-rh 113 k
 rh-java-common-slf4j-api           noarch 1.7.4-3.22.el7  centos-sclo-rh  33 k
 rh-java-common-slf4j-simple        noarch 1.7.4-3.22.el7  centos-sclo-rh  20 k
 rh-maven33-aether-api              noarch 1:1.0.2-3.2.el7 centos-sclo-rh 129 k
 rh-maven33-aether-connector-basic  noarch 1:1.0.2-3.2.el7 centos-sclo-rh  40 k
 rh-maven33-aether-impl             noarch 1:1.0.2-3.2.el7 centos-sclo-rh 162 k
 rh-maven33-aether-spi              noarch 1:1.0.2-3.2.el7 centos-sclo-rh  31 k
 rh-maven33-aether-transport-wagon  noarch 1:1.0.2-3.2.el7 centos-sclo-rh  29 k
 rh-maven33-aether-util             noarch 1:1.0.2-3.2.el7 centos-sclo-rh 133 k
 rh-maven33-aopalliance             noarch 1.0-8.8.el7     centos-sclo-rh  12 k
 rh-maven33-apache-commons-lang3    noarch 3.4-2.2.el7     centos-sclo-rh 396 k
 rh-maven33-cdi-api                 noarch 1.0-11.SP4.13.el7
                                                           centos-sclo-rh  42 k
 rh-maven33-google-guice            noarch 4.0-2.7.el7     centos-sclo-rh 454 k
 rh-maven33-jboss-ejb-3.1-api       noarch 1.0.2-10.12.el7 centos-sclo-rh  55 k
 rh-maven33-jboss-el-2.2-api        noarch 1.0.1-0.7.20120212git2fabd8.13.el7
                                                           centos-sclo-rh  45 k
 rh-maven33-jboss-interceptors-1.1-api
                                    noarch 1.0.2-0.9.20120319git49a904.11.el7
                                                           centos-sclo-rh  28 k
 rh-maven33-jsr-305                 noarch 0-0.18.20090319svn.11.el7
                                                           centos-sclo-rh  29 k
 rh-maven33-maven-wagon-file        noarch 2.10-1.3.el7    centos-sclo-rh  20 k
 rh-maven33-maven-wagon-http        noarch 2.10-1.3.el7    centos-sclo-rh  42 k
 rh-maven33-maven-wagon-http-shared noarch 2.10-1.3.el7    centos-sclo-rh  21 k
 rh-maven33-maven-wagon-provider-api
                                    noarch 2.10-1.3.el7    centos-sclo-rh  57 k
 rh-maven33-plexus-cipher           noarch 1.7-5.16.el7    centos-sclo-rh  23 k
 rh-maven33-plexus-classworlds      noarch 2.5.2-3.5.el7   centos-sclo-rh  60 k
 rh-maven33-plexus-containers-component-annotations
                                    noarch 1.5.5-14.22.el7 centos-sclo-rh  13 k
 rh-maven33-plexus-interpolation    noarch 1.21-3.2.el7    centos-sclo-rh  60 k
 rh-maven33-plexus-sec-dispatcher   noarch 1.4-13.12.el7   centos-sclo-rh  30 k
 rh-maven33-plexus-utils            noarch 3.0.22-2.2.el7  centos-sclo-rh 238 k
 rh-maven33-runtime                 x86_64 1-17.el7        centos-sclo-rh  33 k
 rh-maven33-sisu-inject             noarch 1:0.3.2-2.5.el7 centos-sclo-rh 330 k
 rh-maven33-sisu-plexus             noarch 1:0.3.2-2.5.el7 centos-sclo-rh 174 k
 scl-utils                          x86_64 20130529-17.el7_1
                                                           base            24 k
 tcp_wrappers-libs                  x86_64 7.6-77.el7      base            66 k
 which                              x86_64 2.20-7.el7      base            41 k
```
</details>

Not only does the image size nearly doubles and increases with about 100 MB, most of these packages are absolutely unnecessary and also might introduce security risks, simply because they are there, increasing the attack surface. 

Why do one want to have

* Java 7 (in addition to Java 8 included in the base image)
* GConf2
* X11
* Mesa
* Pango
* Pulseaudio
* libvorbis
* libtiff
* GTK2
* CUPS
* ....

in a server image running in a security sensitive environment like OpenShift ? For Java 7 I know that there are some efforts to remove at least Java 7 from this list, but for the time being it will be released alongside.

Also since only source S2I needs Maven, in the 'typical' usecase of a binary build, even Maven is unnecessary baggage. Maybe a good plan for the future could be to have separate images for S2I source (with Maven) and binary (without Maven) ? 

If you need this for the the RHEL image for FIS 2.0 I'm somewhat ok with having this in the product images if it must be. But for the upstream I would like to keep this out.

wdyt @chirino @dsimansk @jamesnetherton @jimmidyson ?

**Comment by jimmidyson** [comment]
Might be a good idea now to not self merge before any review?

**Comment by dsimansk** [comment]
@rhuss yes it's required for RHEL image to have only signed rpms. That's the motivation of this PR. I don't see any necessity to have SCL's Maven in upsteam image though.

There're several other efforts, but with the timeframe further than FIS 2.0 release. SCL team was requested to divide rpms or at least remove Java 7, afaik. Plus there're some plans to have sidecar container with s2i necessary tools. And you're right, we endors s2i binary in the documentation of FIS 2.0 tech preview release, but common s2i support is still required.

**Comment by chirino** [comment]
reference: https://issues.jboss.org/browse/OSFUSE-387

**Comment by jamesnetherton** [comment]
I think we should confine this change to the RHEL images. 

If we can shave off 100MB from the community image size and keep out unwanted stuff by installing directly from the tar archive, then it's worth doing IMO.

**Pull request merged**
