### PR TITLE
ported ENTESB-10252: no_proxy in jvm argument not honoured in FIS Image

### PR DESCRIPTION
**Pull request by valdar**
original fix: https://github.com/fabric8io-images/s2i/commit/3390cc4d45831caf70f0becdb6383d8ccd7e5f12
more info: https://issues.jboss.org/browse/ENTESB-10252?focusedCommentId=13702157&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13702157

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Looks ok....

I guess the bump to run-java v1.3.3 is why this change also pulls in a whole bunch of unrelated stuff? Like compatibility for JDKs > 8.

Wondering if it would be safer to create a redhat branch on the run-java project off of the v1.2.2 tag. Then we can reference that branch on fuse-7.x.redhat in this project and just consume minimal changes. I think we did a similar thing for FIS 2.0, guess we forgot to do it for Fuse 7.

WDYT?

**Comment by valdar** [comment]
I guess it is safer. Let's do that.

**Comment by jamesnetherton** [comment]
New branch here:

https://github.com/fabric8io-images/run-java-sh/tree/fuse-7.x.redhat

**Comment by valdar** [comment]
useful changes cherry-picked here https://github.com/fabric8io-images/run-java-sh/pull/88 and PR updated accordingly.

**Pull request closed without merging**
