### PR TITLE
use test.sh in circle.yml (re. #120)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@rhuss something like this, for #120 ? This is UNTESTED and my blind attempt / guess...

**Review by rhuss — COMMENTED** [review]
Actually this will not be that simple as we have to install some stuff before running the test:

* s2i tools
* fish-pepper

For the latter (and maybe even for the former) we could use given Docker image which includes these tools.

Let give me a try later.

**Comment by vorburger** [comment]
#223 would help with half of what's required here - fish-pepper would be a non-issue.

s2i tools in container would be much more interesting.. wouldn't that require "docker in docker" ? I don't think that is feasible, or something that I would have cycles for sinking significant time into further investigating...

**Comment by vorburger** [comment]
Whoa! I'm cleaning up many of my very old open PRs, from MANY years ago.. closing!

**Pull request closed without merging**
