### PR TITLE
Fix #113 broken build (jboss home directory is in /opt not /home)

### LINKED ISSUE #113: chmod: cannot access '/home/jboss': No such file or directory
Unless I'm misunderstanding something, this is currently broken? See this:

    docker build https://github.com/fabric8io-images/s2i.git#master:java/images/jboss

hits this:

```
(...)
Removing intermediate container 0c135ef3fbca
Step 24/28 : RUN mkdir -p /deployments/data  && chmod -R "g+rwX" /deployments  && chown -R jboss:root /deployments  && chmod -R "g+rwX" /home/jboss  && chown -R jboss:root /home/jboss  && chmod 664 /etc/passwd
 ---> Running in d6a33b78d783
chmod: cannot access '/home/jboss': No such file or directory
The command '/bin/sh -c mkdir -p /deployments/data  && chmod -R "g+rwX" /deployments  && chown -R jboss:root /deployments  && chmod -R "g+rwX" /home/jboss  && chown -R jboss:root /home/jboss  && chmod 664 /etc/passwd' returned a non-zero code: 1
```

same [if you do it like in the circle.yml](https://github.com/fabric8io-images/s2i/blob/master/circle.yml#L22):

    git clone git@github.com:fabric8io-images/s2i.git
    cd images/jboss
    docker build -t fabric8/s2i-java:latest .

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
Now that I got [fish-pepper](https://github.com/fabric8io-images//issues/12) working (thanks to @mojavelinux  in https://github.com/fabric8io-images//issues/12!), I've fixed this in the correct place - in the template instead of the generated Dockerfile.

**Comment by jamesnetherton** [comment]
This would fix the jboss community image but break the RHEL image. `/home/jboss` is the correct path for the RHEL image.

**Comment by ctron** [comment]
I think you could re-write the dockerfile so that it would work with both directories, by checking for their existence first.

**Comment by jamesnetherton** [comment]
@vorburger yes, maybe it's better if the home directory path is a variable that could be used in the Dockerfile template. That way there's less chance for people to get things wrong in future.

If we are going to align images, then it's the [community image](https://github.com/jboss-dockerfiles/base) that should change IMO. Not sure how practical that is in reality, given how many images use it as their parent.

@rhuss any thoughts on this?

**Comment by rhuss** [comment]
> @jamesnetherton oups, OK.. Then I guess we (I'm willing to..) could make a new variable for the correct path in the template and then specify it as /home/jboss VS /opt/jboss in the images.yml ? Or do you guys prefer it with {? fp.param.base === "rhel"}} - I could just move it into the respective block just below which does this for COPY settings.xml ?

Sound both legit to me, the variable approach sounds more flexible to me. Happy to take a PR and integrate it.

**Comment by rhuss** [comment]
@vorburger :

> Now that I got fish-pepper working (thanks to @mojavelinux in @fabric8io-images!), I've fixed this in the correct place - in the template instead of directly in only 1 instead of 2 of the generated Dockerfiles.

yeah, fish-pepper. I had the plan to rewrite it to go (as node doesn't to pay off really for that kind of task), but maybe we are all switching completely to https://github.com/cekit/cekit/ (used by CE for their images), just to have some moving parts less ?

**Comment by vorburger** [comment]
> could make a new variable for the correct path in the template

OK, that's now done - do you like this @jamesnetherton and @rhuss ?

> Happy to take a PR and integrate it.

This one (#114) *IS* the PR... ;) and #113 is the related, which gets closed when you merge this.

> yeah, fish-pepper. I had the plan to rewrite it

do you want to open a separate issue for that plan? :smile:

**Comment by dhirajsb** [comment]
@vorburger the same change needs to go into karaf images as well.

**Comment by dhirajsb** [comment]
Merging this, will create another PR for karaf image changes.

**Pull request merged**
