### PR TITLE
Add prometheus as a javaagent, add config and script support for prometheus

### PR DESCRIPTION
**Pull request by cunningt**
Add prometheus as a javaagent, add config and script support for prometheus

### CODE REVIEW

**Comment by dhirajsb** [comment]
@cunningt it looks like you made the changes directly to the ```jboss/*``` and ```rhel/*``` files. We use [fish-pepper|https://github.com/fabric8io-images/fish-pepper], which uses template files in ```templates/*``` and generates the jboss and rhel images. 

Please make your changes to the template files (where appropriate, some files may be image specific) and run fish-pepper to re-generate image files? 

The PR should include both updates to templates and the generates images (since our Jenkins pipelines do not currently use fish-pepper to update the image files).

**Comment by cunningt** [comment]
@dhirajsb : I went ahead and added the fish-pepper changes (sorry about missing that the first time).   I added a local block for the prometheus changes, and I've gone through and tested the jboss java and karaf images - prometheus seems to start and the metrics seem to be exposed on 9779 for me in minishift.

**Comment by dhirajsb** [comment]
@cunningt LGTM, thanks!

**Comment by rhuss** [comment]
@cunningt @dhirajsb Sorry, the PR escaped under my radar, but I wonder why not leveraging agent-bond which contains both, Jolokia and jmx_exporter ? (actually that's the whole idea of agent-bond to have only a single agent to attach).

**Comment by cunningt** [comment]
@rhuss I think we decided on using jmx_exporter vs. agent-bond for maintenance (update jmx_exporter version directly rather than have to update agent-bond, release, update agent-bond version), but I think the long term plan may be to replace the jmx_exporter here with the hawkular java agent, which will include the jmx exporter and offer a secured http endpoint.

**Pull request merged**
