### PR TITLE
Add JAVA_MAJOR_VERSION

### LINKED ISSUE #213: JAVA_DIAGNOSTICS for s2i java 11 image uses deprecated and removed JVM options
Options such as PrintGCDateStamps are no longer valid.

### PR DESCRIPTION
**Pull request by muff1nman**
In combination with https://github.com/fabric8io-images/run-java-sh/pull/78, this should resolve #213.

### CODE REVIEW

**Comment by vorburger** [comment]
@muff1nman I think this is going in the right direction and I'm in favour of this, but:

Similarly to the previous discussion over in #217, you cannot (only) change the `java/images/**/Dockerfile` ... if you run the `./test.sh` at the root which runs `fish-pepper` then you'll see that the changes you propose here would just get overwritten (soon) and lost again.

Instead, change the  `[s2i/java/templates/Dockerfile](https://github.com/fabric8io-images/s2i/blob/master/java/templates/Dockerfile)` and use a variable you set in `[s2i/java/images.yml](https://github.com/fabric8io-images/s2i/blob/master/java/images.yml)` - in fact, while I'm looking at this it seems to me you'll probably really just want to use the already existing (which I introduced...) `javaMajor` ?

Does this make sense and do you think you can do this?

**Comment by rhuss** [comment]
I agree with @vorburger . Installing fish-pepper might be a pain, so I recommend to run it from within a Docker container like in 

```
docker run -it --rm -v $(pwd):/fp fabric8/fish-pepper
```

(of course you need to able to use volume mounts)

See also https://github.com/fabric8io-images/fish-pepper/tree/master/docker

**Comment by muff1nman** [comment]
@vorburger Ended up going with a second variable to be explicit.

**Comment by vorburger** [comment]
> @vorburger Ended up going with a second variable to be explicit.

OK for me... in an ideal world, you would also contribute an extension to `test.sh` to cover for future non-regression of #213 .. do you think you may have time to add that here?

> In combination with [fabric8io-images/run-java-sh#78](https://github.com/fabric8io-images/run-java-sh/pull/78), this should resolve #213.

but don't you have to bump the version of run-java-sh in `java/fish-pepper.yml` as part of this PR now? Or is https://github.com/fabric8io-images/run-java-sh/pull/78 in 1.3.0 already? FYI v1.3.1 is broken, watch #123 .. we'll probably have a 1.3.2.

**Comment by vorburger** [comment]
@muff1nman do you want to finish this one up? I think following #123 which bumped run-java-sh you just have to debase this on the latest master now, and then it will work..

**Comment by muff1nman** [comment]
@vorburger Rebased. I tested it and after increasing the `app_test` sleep time it worked. Probably a slightly starved VM and/or older cpu with not very good single thread perfomance. So I think this is good to go.

**Pull request merged**
